# Generated by Django 5.1.5 on 2025-01-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sede',
        ),
        migrations.AddField(
            model_name='kardex',
            name='sede',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='menu.sede'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sede')),
            ],
        ),
    ]
