# Generated by Django 5.1.5 on 2025-01-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cliente_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
