# Generated by Django 5.1.5 on 2025-01-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_venta_cancelada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin', models.BooleanField(default=False)),
                ('es_usuario', models.BooleanField(default=False)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='menu.sede')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
