# Generated by Django 5.1.5 on 2025-02-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='menu.sede'),
        ),
    ]
